spring:
  application:
    name: spring-data-jpa-specification-qbe
  jpa:
    hibernate:
      ddl-auto: none
    properties :
      hibernate:
        show_sql: true
        format_sql: true
